2024-10-22 18:49:29,316 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 39, in start_simulation
    renderer = Renderer()
               ^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\visualization\render_3d.py", line 15, in __init__
    glutInit()
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
2024-10-23 07:59:04,270 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 35, in start_simulation
    glutInit()
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
2024-10-23 08:04:21,145 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 53, in start_simulation
    glutInit()
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
2024-10-23 08:04:55,967 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 53, in start_simulation
    glutInit()
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\GabrielRocca\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
2024-10-23 08:43:04,990 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 72, in start_simulation
    space.update(spaceship)  # Passa a nave como argumento
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\space.py", line 74, in update
    distance = self.distance_from_last_sector(spaceship.position)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\space.py", line 62, in distance_from_last_sector
    distance = Physics.calculate_distance_from_coords(self.last_sector_position, spaceship_position)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Physics' has no attribute 'calculate_distance_from_coords'
2024-10-23 11:34:44,357 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 76, in start_simulation
    camera.update_position_with_keyboard(keys)  # Movimenta a câmera com W, A, S, D, Espaço, Shift
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\visualization\camera.py", line 69, in update_position_with_keyboard
    if keys[pygame.K_w]:  # Tecla W
            ^^^^^^
NameError: name 'pygame' is not defined
2024-10-23 12:49:22,001 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 154, in start_simulation
    space.update(spaceship)  # Passa a nave como argumento
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\space.py", line 90, in update
    distance = Physics.calculate_distance(spaceship.position, obj.position)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\physics.py", line 33, in calculate_distance
    (obj1.position[0] - obj2.position[0]) ** 2 +
     ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'position'
2024-10-23 13:42:22,076 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 142, in start_simulation
    spaceship.update(delta_time, keys)  # Passa delta_time e keys
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Spaceship.update() takes 2 positional arguments but 3 were given
2024-10-23 13:44:29,214 - ERROR - Error in start_simulation
Traceback (most recent call last):
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\main.py", line 142, in start_simulation
    spaceship.update(delta_time, keys)  # Passa delta_time e keys
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\spaceship.py", line 59, in update
    self.velocity[0] = Physics.calculate_velocity(self.velocity[0], self.acceleration[0], time_step)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GabrielRocca\source\repos\games\eternal-space\src\simulation\physics.py", line 18, in calculate_velocity
    velocity[0] + acceleration[0] * time_step,
    ~~~~~~~~^^^
TypeError: 'float' object is not subscriptable
